---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
options:
  package_manager_path: /usr/bin/microdnf
  skip_ansible_check: true

additional_build_files:
  # - src: ansible.cfg
  #   dest: configs
  - src: requirements-pip2.txt
    dest: configs
  # - src: libnl-1.1.4-3.el7.i686.rpm
  #   dest: configs
  - src: python-ethtool-0.8-8.el7.x86_64.rpm
    dest: configs
  - src: python-dmidecode-3.12.2-4.el7.x86_64.rpm
    dest: configs

additional_build_steps:
  prepend_builder:
    - RUN python3 -m pip uninstall -y ansible
  append_builder:
    - ADD _build/configs/requirements-pip2.txt /tmp/requirements-pip2.txt
#     - RUN ansible --version
    - RUN python2 -m pip install -r /tmp/requirements-pip2.txt
    - ADD _build/configs/python-ethtool-0.8-8.el7.x86_64.rpm /tmp/python-ethtool-0.8-8.el7.x86_64.rpm
    - RUN rpm -i /tmp/python-ethtool-0.8-8.el7.x86_64.rpm
    - ADD _build/configs/python-dmidecode-3.12.2-4.el7.x86_64.rpm /tmp/python-dmidecode-3.12.2-4.el7.x86_64.rpm
    - RUN rpm -i /tmp/python-dmidecode-3.12.2-4.el7.x86_64.rpm

dependencies:

  system:
    - python2
    - python2-pip


  python:
    - adal==1.2.2
    - ansible==2.9.27
    - ansible-tower-cli==3.3.9
    - apache-libcloud==2.5.0
    - appdirs==1.4.3
    - applicationinsights==0.11.9
    - argcomplete==1.10.3
    - azure-cli-core==2.0.35
    - azure-cli-nspkg==3.0.2
    - azure-common==1.1.11
    - azure-graphrbac==0.40.0
    - azure-keyvault==1.0.0a1
    - azure-mgmt-authorization==0.51.1
    - azure-mgmt-automation==0.1.1
    - azure-mgmt-batch==5.0.1
    - azure-mgmt-cdn==3.0.0
    - azure-mgmt-compute==4.4.0
    - azure-mgmt-containerinstance==1.4.0
    - azure-mgmt-containerregistry==2.0.0
    - azure-mgmt-containerservice==4.4.0
    - azure-mgmt-cosmosdb==0.5.2
    - azure-mgmt-devtestlabs==3.0.0
    - azure-mgmt-dns==2.1.0
    - azure-mgmt-hdinsight==0.1.0
    - azure-mgmt-iothub==0.7.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-loganalytics==0.2.0
    - azure-mgmt-marketplaceordering==0.1.0
    - azure-mgmt-monitor==0.5.2
    - azure-mgmt-network==2.3.0
    - azure-mgmt-nspkg==2.0.0
    - azure-mgmt-rdbms==1.4.1
    - azure-mgmt-redis==5.0.0
    - azure-mgmt-resource==2.1.0
    - azure-mgmt-servicebus==0.5.3
    - azure-mgmt-sql==0.10.0
    - azure-mgmt-storage==3.1.0
    - azure-mgmt-trafficmanager==0.50.0
    - azure-mgmt-web==0.41.0
    - azure-nspkg==2.0.0
    - azure-storage==0.35.1
    - Babel==0.9.6
    - backports.ssl-match-hostname==3.5.0.1
    - bcrypt==3.1.7
    - boto==2.47.0
    - boto3==1.9.223
    - botocore==1.12.253
    - cachetools==3.1.1
    - certifi==2038.12.31
    - cffi==1.13.2
    - chardet==3.0.4
    - click==6.7
    - colorama==0.4.3
    # - configobj==4.7.2
    - cryptography==2.8
    - decorator==4.4.1
    - docutils==0.15.2
    - dogpile.cache==0.9.0
    # - enum34==1.1.6
    - et-xmlfile==1.0.1
    # - ethtool==0.8
    # - futures==3.3.0
    - google-auth==1.6.2
    - httplib2==0.18.1
    - humanfriendly==4.18
    - idna==2.8
    - iniparse==0.4
    # - ipaddr==2.1.11
    - ipaddress==1.0.23
    - IPy==0.75
    - iso8601==0.1.12
    - isodate==0.6.0
    - jdcal==1.4.1
    - Jinja2==2.10.1
    - jmespath==0.9.4
    - jsonpatch==1.24
    - jsonpointer==2.0
    - keystoneauth1==3.18.0
    # - kitchen==1.1.1
    - knack==0.3.3
    - kubernetes==11.0.0
    - lxml==4.4.2
    # - M2Crypto==0.21.1
    # - Magic-file-extensions==0.2
    - MarkupSafe==1.1.1
    # - meld3==0.6.10
    # - mercurial==2.6.2
    - monotonic==1.5
    - msrest==0.6.1
    - msrestazure==0.5.0
    - munch==2.5.0
    - ncclient==0.6.3
    - netaddr==0.7.19
    - netapp-lib==2020.7.16
    - netifaces==0.10.9
    - ntlm-auth==1.4.0
    - oauthlib==3.1.0
    - openshift==0.11.2
    - openstacksdk==0.37.0
    - os-service-types==1.7.0
    - ovirt-engine-sdk-python==4.3.0
    - packaging==19.2
    - paramiko==2.7.1
    - pbr==5.4.4
    # - pciutils==1.7.3
    # - perf==0.1
    # - pexpect==2.3
    - ply==3.4
    # - policycoreutils-default-encoding==0.1
    - psutil==5.7.0
    # - psycopg2==2.5.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pycparser==2.19
    # - pycurl==7.43.0.1
    - Pygments==2.5.2
    # - pygobject==3.22.0
    # - pygpgme==0.3
    - pyinotify==0.9.4
    - PyJWT==1.7.1
    - pykerberos==1.2.1
    # - pyliblzma==0.5.3
    - PyNaCl==1.4.0
    - pyOpenSSL==19.1.0
    - pyparsing==2.4.5
    - python-dateutil==2.8.1
    # - python-dmidecode==3.10.13
    # - python-ldap==2.4.15
    # - python-linux-procfs==0.4.9
    # - python-qpid-proton==0.34.0
    - python-string-utils==0.6.0
    - pyudev==0.15
    - pyvmomi==6.7.3
    - pywinrm==0.3.0
    # - pyxattr==0.5.1
    - PyYAML==5.2
    - requests==2.22.0
    - requests-credssp==1.0.2
    - requests-kerberos==0.12.0
    - requests-ntlm==1.1.0
    - requests-oauthlib==1.3.0
    - requestsexceptions==1.4.0
    - rsa==4.5
    # - ruamel.ordereddict==0.4.14
    - ruamel.yaml==0.16.10
    - ruamel.yaml.clib==0.2.0
    - s3transfer==0.2.1
    # - schedutils==0.4
    - selectors2==2.0.1
    # - seobject==0.1
    # - sepolicy==1.1
    - six==1.13.0
    # - slip==0.4.0
    # - slip.dbus==0.4.0
    # - SSSDConfig==1.16.5
    - stevedore==1.31.0
    # - supervisor==3.4.0
    # - syspurpose==1.24.53
    - tabulate==0.8.2
    # - typing==3.7.4.1
    # - urlgrabber==3.10
    - urllib3==1.25.7
    - virtualenv==15.1.0
    - virtualenv-clone==0.5.4
    - websocket-client==0.57.0
    - XlsxWriter==2.0.0
    - xmltodict==0.12.0
    # - yum-metadata-parser==1.1.4

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-29-rhel8:latest
