---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
options:
  package_manager_path: /usr/bin/microdnf
  skip_ansible_check: true

additional_build_files:
  - src: requirements-pip2.txt
    dest: configs

additional_build_steps:
  prepend_builder:
    - RUN python3 -m pip uninstall -y ansible

dependencies:

  system:
    - python2
    - python2-pip


  python:
    - ansible==4.6.0
    - ansible-core==2.11.5
    - cffi==1.14.6
    - cryptography==3.4.8
    - Jinja2==3.0.1
    - MarkupSafe==2.0.1
    - packaging==21.0
    - psutil==5.8.0
    - pycparser==2.20
    - pyparsing==2.4.7
    - PyYAML==5.4.1
    - resolvelib==0.5.4


images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-29-rhel8:latest
