- set_fact:
    export_output_inventories: []
    export_output_inventorie_sources: []
    export_output_inventories_aux2: []
    export_output_inventorie_sources_aux_workflow2: []

- name: Export inventory tower
  awx.awx.export:
    inventory: "{{ item.inventory.name }}"
    controller_host: "{{ controller_hostname_old }}"
    controller_username: "{{ controller_username_old }}"
    controller_password: "{{ controller_password_old }}"
    validate_certs: "{{ controller_validate_certs_old }}"
  register: export_output_inventories_aux
  when: 
  - item.inventory is defined
  - item.inventory
  loop: "{{export_job_templates_output|union(controller_workflows|default([]))}}"

- name: Export inventory tower from workflow
  awx.awx.export:
    inventory: "{{ item.name }}"
    controller_host: "{{ controller_hostname_old }}"
    controller_username: "{{ controller_username_old }}"
    controller_password: "{{ controller_password_old }}"
    validate_certs: "{{ controller_validate_certs_old }}"
  register: export_output_inventories_aux_workflow
  loop: "{{list_inventories_execute|default([])}}"

- debug:
    msg: "{{export_output_inventories_aux}}"

- debug:
    msg: "{{export_output_inventories_aux.results}}"

- set_fact:
    export_output_inventories_aux2: "{{export_output_inventories_aux2|union(item.assets.inventory)}}"
  when: item.assets is defined
  loop: "{{export_output_inventories_aux.results|union(export_output_inventories_aux_workflow.results)}}"

- debug:
    msg: "{{export_output_inventories_aux2}}"

- set_fact:
    export_output_inventories: "{{export_output_inventories|union(export_output_inventories_aux2|selectattr('name','eq',item.inventory.name)|selectattr('organization.name','eq',item.inventory.organization.name))}}"
  when: 
    - item.inventory is defined 
    - item.inventory
  loop: "{{export_job_templates_output|union(controller_workflows|default([]))}}"

- set_fact:
    export_output_inventories: "{{export_output_inventories|union(export_output_inventories_aux2|selectattr('name','eq',item.name)|selectattr('organization.name','eq',item.organization))}}"
  loop: "{{list_inventories_execute|default([]))}}"

- debug:
    msg: "{{export_output_inventories}}"

- set_fact:
    controller_inventories_content: |-
      {"controller_inventories":
        [
        {% for inventory_info in export_output_inventories %}
          {
          "description": "{{inventory_info.description}}",
          {%- if inventory_info.host_filter -%}
          "host_filter": "{{inventory_info.host_filter}}",
          {% endif %}
          "kind": "{{inventory_info.kind}}",
          "name": "{{inventory_info.name}}",
          "organization": {{inventory_info.organization}},
          {%- if inventory_info.variables | from_yaml -%}
          "variables": {{inventory_info.variables| from_yaml }}
          {% endif %}
          },
        {% endfor %}
        ]
      }

- debug:
    msg: "{{controller_inventories_content}}"

- set_fact:
    controller_inventories: "{{controller_inventories_content.controller_inventories}}"

- debug:
    msg: "{{controller_inventories}}"

- copy: content="{{ controller_inventories_content | to_yaml}}" dest="{{folder_project_export_dest}}/controller_inventories.yml"

- name: Export inventory_sources tower from workflow
  awx.awx.export:
    inventory_sources: "{{ item.name }}"
    controller_host: "{{ controller_hostname_old }}"
    controller_username: "{{ controller_username_old }}"
    controller_password: "{{ controller_password_old }}"
    validate_certs: "{{ controller_validate_certs_old }}"
  register: export_output_inventorie_sources_aux_workflow
  loop: "{{list_inventorie_sources_execute|default([])}}"

- debug:
    msg: "{{export_output_inventorie_sources_aux_workflow}}"

- set_fact:
    controller_inventory_sources_content: |-
      {"controller_inventory_sources":
        [
        {% for inventory_source_result in export_output_inventorie_sources_aux_workflow.results %}
          {% for inventory_source_info in inventory_source_result.assets.inventory_sources %}
          {
          "credential": {{inventory_source_info.credential}},
          {%- if inventory_source_info.custom_virtualenv -%}
          "custom_virtualenv": {{inventory_source_info.custom_virtualenv}},
          {% endif %}
          "description": "{{inventory_source_info.description}}",
          "enabled_value": "{{inventory_source_info.enabled_value}}",
          "enabled_var": "{{inventory_source_info.enabled_var}}",
          "host_filter": "{{inventory_source_info.host_filter}}",
          {%- if inventory_source_info.inventory -%}
          "inventory": {{inventory_source_info.inventory}},
          {% endif %}
          "name": "{{inventory_source_info.name}}",
          "overwrite": {{inventory_source_info.overwrite}},
          "overwrite_vars": {{inventory_source_info.overwrite_vars}},
          "related": {{inventory_source_info.related}},
          "source": "{{inventory_source_info.source}}",
          "source_path": "{{inventory_source_info.source_path}}",
          "source_project": {{inventory_source_info.source_project}},
          {%- if inventory_source_info.source_script -%}
          "source_script": {{inventory_source_info.source_script}},
          {% endif %}
          {%- if inventory_source_info.source_vars -%}
          "source_vars": {{inventory_source_info.source_vars| from_yaml}},
          {% endif %}
          "timeout": {{inventory_source_info.timeout}},
          "update_cache_timeout": {{inventory_source_info.update_cache_timeout}},
          "update_on_launch": {{inventory_source_info.update_on_launch}},
          "update_on_project_update": {{inventory_source_info.update_on_project_update}},
          "verbosity": {{inventory_source_info.verbosity}}
          },
          {% endfor %}
        {% endfor %}
        ]
      }

- debug:
    msg: "{{controller_inventory_sources_content}}"

- set_fact:
    controller_inventory_sources: "{{controller_inventory_sources_content.controller_inventory_sources}}"

- debug:
    msg: "{{controller_inventory_sources}}"

- copy: content="{{ controller_inventory_sources_content | to_yaml}}" dest="{{folder_project_export_dest}}/controller_inventory_sources.yml"


- set_fact:
    export_output_inventories_aux: ""
    export_output_inventories_aux_workflow: ""