
- name: Creates directory
  ansible.builtin.file:
    path: "repo_dest"
    state: absent

- name: Creates directory
  ansible.builtin.file:
    path: "repo_dest"
    state: directory

- name: Git checkout
  ansible.builtin.git:
    repo: 'git@github.axa.com:axaes-ops/axaes-aap-iaas-code.git'
    dest: repo_dest
    version: main


- name: call the slave playbook
  include_tasks: merge_components_files.yml
  loop:
    - name: controller_credentials
      encrypt: true
      config: "{{controller_credentials_content| default([]) }}"
    - name: controller_credential_types
      encrypt: false
      config: "{{controller_credential_types_content| default([]) }}"
    - name: controller_inventories
      encrypt: false
      config: "{{controller_inventories_content| default([]) }}"
    - name: controller_templates
      encrypt: false
      config: "{{controller_job_templates_content| default([]) }}"
    - name: controller_organizations
      encrypt: false
      config: "{{controller_organizations_content| default([]) }}"
    - name: controller_projects
      encrypt: false
      config: "{{controller_projects_content| default([]) }}"
    - name: controller_schedules
      encrypt: false
      config: "{{controller_schedules_content| default([]) }}"
    - name: controller_workflows
      encrypt: false
      config: "{{controller_workflows_content| default([]) }}"
    - name: controller_credential_input_sources
      encrypt: false
      config: "{{controller_credential_input_sources_content| default([]) }}"
    - name: controller_inventory_sources
      encrypt: false
      config: "{{controller_inventory_sources_content| default([]) }}"
    - name: controller_labels
      encrypt: false
      config: "{{controller_labels_content| default([]) }}"
    - name: controller_notifications
      encrypt: false
      config: "{{controller_notifications_content| default([]) }}"

- name: Publish the changes
  ansible.scm.git_publish:
    path: "repo_dest"
