- debug:
    msg: "{{source_credential_vaults}}"
  tags:
    - debug
    - debug_credentials
  when: source_credential_vaults is defined 

- debug:
    msg: "{{export_output_source_credential}}"
  tags:
    - debug
    - debug_credentials
    
- debug:
    msg: "{{item}}"
  tags:
    - debug
    - debug_credentials

- name: Iterate Input SOurce Credential
  block:
  - name: Set facts
    set_fact:
      export_output_source_credential: "{{ export_output_source_credential| union([source_credential_vaults[item.name]])}}"
  when: source_credential_vaults is defined and item.name in source_credential_vaults
