---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
options:
  package_manager_path: /usr/bin/microdnf


dependencies:
  galaxy:
    collections:
      - name: infra.controller_configuration
      - name: awx.awx 

  python_interpreter:
    python_path: "/usr/bin/python3"
    package_system: "python3"

  

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.16.3-1
    # name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:1.0.0-527



