---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    lista_extra_vars:
      - "mm_password"
      - "mm_username"
      - "ansible_user"
      - "ansible_password"
      - "ansible_user"
      - "ansible_password"
      - "github_password"
      - "github_username"
      - "ldap_pass"
      - "ldap_user"
      - "maam_client"
      - "maam_client_secret"
      - "maam_access_token"
      - "clearpass_secret"
      - "clearpass_client_id"
      - "proxy_pass"
      - "proxy_user"
      - "scp_password"
      - "scp_username"
      - "win_runas_pass"
      - "win_runas_user"
      - "win_runas_domain"
      - "domain_admin_password"
      - "scm_username"
      - "scm_password"
    lista_env:
      - "TOWER_HOST"
      - "TOWER_USERNAME"
      - "TOWER_PASSWORD"
      - "TOWER_VERIFY_SSL"
      - "TOWER_OAUTH_TOKEN"
      - "AZURE_DEVOPS_PASSWORD"
      - "AZURE_DEVOPS_USERNAME"
      - "JFROG_AUTH_HOST"
      - "JFROG_AUTH_API_KEY"
      - "JFROG_AUTH_USERNAME"
      - "F5_USER"
      - "F5_PASSWORD"
      - "K8S_AUTH_HOST"
      - "K8S_AUTH_API_KEY"
      - "K8S_AUTH_USERNAME"
      - "OVIRT_INI_PATH"
      - "OVIRT_URL"
      - "OVIRT_USERNAME"
      - "OVIRT_PASSWORD"
      - "SN_PASSWORD"
      - "SN_USERNAME"
  tasks:

  #- set_fact:
  #    envs_credential_list: |-
  #      {"{{ name_credential }}":
  #        { "{{ name_organization }}":
  #          {
  #          {% for name_env in lista_env %}
  #            {%- if lookup("env", name_env) -%}
  #            "{{ name_env }}": "{{ lookup('env', name_env) }}",
  #            {% endif %}
  #          {% endfor %}
  #          }
  #        }
  #      }

  #- debug:
  #    msg: "{{ envs_credential_list }}"

  #- debug: 
  #    msg: '{{ hostvars[inventory_hostname][item]|default("") }}'
  #  ignore_errors: yes
  #  loop: "{{ lista_extra_vars }}"
  
  - set_fact:
      injector_credentials: |-
        {"{{ name_credential }}":
          { "{{ name_organization }}":
            { "inputs":
              [
              {% for name_env in lista_env %}
                {%- if lookup("env", name_env) -%}
                {
                "{{ name_env }}": "{{ lookup('env', name_env) }}"
                },
                {% endif %}
              {% endfor %}
              {% for name_env in lista_extra_vars %}
                {%- if hostvars[inventory_hostname][name_env]|default("") -%}
                {
                "{{ name_env }}": "{{ hostvars[inventory_hostname][name_env]|default('') }}"
                },
                {% endif %}
              {% endfor %}
              ]
            }
          }
        }

  - debug:
      msg: "{{ injector_credentials }}"

  - name: Set facts
    ansible.builtin.set_stats:
      data:
        injector_credentials: "{{ injector_credentials }}"
      per_host: no