---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yaml
  tasks:

    - name: Queue build of a project in Jenkins
      ansible.builtin.uri:
        url: "https://{{ controller_hostname_old }}/api/v2/"
        user: "{{ controller_username_old }}"
        password: "{{ controller_password_old }}"
        method: GET
        force_basic_auth: true
        validate_certs: "{{controller_validate_certs_old}}"
      register: controller_metrics
      environment:
        HTTP_PROXY: ""
        HTTPS_PROXY: ""
        NO_PROXY: ""
        http_proxy: ""
        https_proxy: ""
        no_proxy: ""

    - name: Export credential_types tower
      awx.awx.export:
        credential_types: "all"
        controller_host: "{{ controller_hostname_old }}"
        controller_username: "{{ controller_username_old }}"
        controller_password: "{{ controller_password_old }}"
        validate_certs: "{{ controller_validate_certs_old }}"
      register: export_output_credential_types

    - debug: 
        msg: "{{ export_output_credential_types }}"

    - set_fact:
        controller_credential_types_content: |-
          {"controller_credential_types":
            [
            {% for credential_type in export_output_credential_types.assets.credential_types %}
              {%- if credential_type.injectors.env is defined -%}
                {% for env_name in credential_type.injectors.env.keys() %}
                  "{{ env_name }}",
                {% endfor %}
              {% endif %}
            {% endfor %}
            ]
          }

    - debug: 
        msg: "{{ controller_credential_types_content }}"


    - set_fact:
        controller_credential_types_content: |-
          {"controller_credential_types":
            [
            {% for credential_type in export_output_credential_types.assets.credential_types %}
              {%- if credential_type.injectors.extra_vars is defined -%}
                {% for env_name in credential_type.injectors.extra_vars.keys() %}
                  "{{ env_name }}",
                {% endfor %}
              {% endif %}
            {% endfor %}
            ]
          }

    - debug: 
        msg: "{{ controller_credential_types_content }}"
