---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
options:
  package_manager_path: /usr/bin/microdnf
  # skip_ansible_check: true


additional_build_steps:
  prepend_builder:
    - RUN python3 -m pip uninstall -y ansible

dependencies:

  python_interpreter:
    python_path: "/usr/bin/python3"
    package_system: "python3"


  python:
    - ansible==2.9.25
    - certifi==2021.5.30
    - cffi==1.14.6
    - charset-normalizer==2.0.6
    - cryptography==35.0.0
    - idna==3.2
    - Jinja2==3.0.2
    - MarkupSafe==2.0.1
    - psutil==5.8.0
    - pycparser==2.20
    - PyYAML==5.4.1
    - requests==2.26.0
    - urllib3==1.26.7

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-29-rhel8:latest
