---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
options:
  package_manager_path: /usr/bin/microdnf
  skip_ansible_check: true


additional_build_steps:
  prepend_builder:
    - RUN python3 -m pip uninstall -y ansible

dependencies:

  system:
    - python2
    - python2-pip


  python:
    - adal==1.2.7
    - ansible==2.9.27
    - ansible-tower-cli==3.3.9
    - applicationinsights==0.11.10
    - argcomplete==1.12.3
    - azure-cli-core==2.11.1
    - azure-cli-nspkg==3.0.2
    - azure-cli-telemetry==1.0.6
    - azure-common==1.1.11
    - azure-core==1.24.0
    - azure-graphrbac==0.61.1
    - azure-keyvault==1.0.0a1
    - azure-mgmt-apimanagement==0.2.0
    - azure-mgmt-authorization==0.51.1
    - azure-mgmt-automation==0.1.1
    - azure-mgmt-batch==5.0.1
    - azure-mgmt-cdn==3.0.0
    - azure-mgmt-compute==10.0.0
    - azure-mgmt-containerinstance==1.4.0
    - azure-mgmt-containerregistry==2.0.0
    - azure-mgmt-containerservice==9.1.0
    - azure-mgmt-core==1.2.0
    - azure-mgmt-cosmosdb==0.5.2
    - azure-mgmt-datalake-nspkg==2.0.0
    - azure-mgmt-datalake-store==0.5.0
    - azure-mgmt-devtestlabs==3.0.0
    - azure-mgmt-dns==2.1.0
    - azure-mgmt-eventhub==2.0.0
    - azure-mgmt-hdinsight==0.1.0
    - azure-mgmt-iothub==0.7.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-loganalytics==1.0.0
    - azure-mgmt-managedservices==1.0.0
    - azure-mgmt-managementgroups==0.2.0
    - azure-mgmt-marketplaceordering==0.1.0
    - azure-mgmt-monitor==0.5.2
    - azure-mgmt-network==12.0.0
    - azure-mgmt-notificationhubs==2.0.0
    - azure-mgmt-nspkg==2.0.0
    - azure-mgmt-privatedns==0.1.0
    - azure-mgmt-rdbms==1.9.0
    - azure-mgmt-recoveryservices==0.4.0
    - azure-mgmt-recoveryservicesbackup==0.6.0
    - azure-mgmt-redis==5.0.0
    - azure-mgmt-resource==10.2.0
    - azure-mgmt-search==3.0.0
    - azure-mgmt-servicebus==0.5.3
    - azure-mgmt-sql==0.10.0
    - azure-mgmt-storage==11.1.0
    - azure-mgmt-trafficmanager==0.50.0
    - azure-mgmt-web==0.41.0
    - azure-nspkg==2.0.0
    - azure-storage==0.35.1
    - bcrypt==3.2.2
    - certifi==2022.5.18.1
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==6.7
    - colorama==0.4.4
    - cryptography==37.0.2
    - humanfriendly==8.2
    - idna==3.3
    - importlib-metadata==4.8.3
    - isodate==0.6.1
    - Jinja2==3.0.3
    - jmespath==0.10.0
    - knack==0.7.2
    - MarkupSafe==2.0.1
    - msal==1.0.0
    - msal-extensions==0.1.3
    - msrest==0.6.10
    - msrestazure==0.6.4
    - oauthlib==3.2.0
    - packaging==21.3
    - paramiko==2.11.0
    - pkginfo==1.8.2
    - portalocker==1.7.1
    - pycparser==2.21
    - Pygments==2.12.0
    - PyJWT==1.7.1
    - PyNaCl==1.5.0
    - pyOpenSSL==22.0.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - PyYAML==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - six==1.16.0
    - tabulate==0.8.9
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - xmltodict==0.13.0
    - zipp==3.6.0

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-29-rhel8:latest
